### ISSUE TITLE
java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation

### ISSUE THREAD

**Issue by Akree** [TinkoffCreditSystems/AcquiringSdkAndroid#7]
Добрый день) 

При попытке открыть экран приема оплаты по QR СБП (openStaticQrScreen) крашится приложение. Причем только на `API 26`, на других версиях все работает)

```console
java.lang.RuntimeException: Unable to start activity ComponentInfo{*/ru.tinkoff.acquiring.sdk.ui.activities.StaticQrActivity}: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2817)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation
        at android.app.Activity.onCreate(Activity.java:986)
        at androidx.core.app.ComponentActivity.onCreate(ComponentActivity.java:81)
        at androidx.activity.ComponentActivity.onCreate(ComponentActivity.java:154)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:312)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
        at ru.tinkoff.acquiring.sdk.ui.activities.BaseAcquiringActivity.onCreate(BaseAcquiringActivity.kt:69)
        at ru.tinkoff.acquiring.sdk.ui.activities.TransparentActivity.onCreate(TransparentActivity.kt:51)
        at ru.tinkoff.acquiring.sdk.ui.activities.StaticQrActivity.onCreate(StaticQrActivity.kt:31)
        at android.app.Activity.performCreate(Activity.java:6975)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
```

**Comment by MaryAPc** [comment]
Здравствуйте! Спасибо за репорт, устраним на этой неделе
